import random
import string
from dataclasses import dataclass, field


import random
import string

def generate_id() -> str:
    """
    Generate a random ID consisting of 15 lowercase letters.

    Returns:
        str: A randomly generated ID.
    """
    return "".join(random.choices(string.ascii_lowercase, k=15))


@dataclass
class Student:
    """
    Represents a student.

    Attributes:
        name (str): The name of the student.
        surname (str): The surname of the student.
        active (bool): Indicates if the student is active.
        login (str): The login name of the student.
        id (str): The unique ID of the student.
    """

    name: str = field(init=True)
    surname: str = field(init=True)
    active: bool = field(default=True)
    login: str = field(init=False)
    id: str = field(init=False, default=generate_id())

    def __post_init__(self):
        """
        Initialize the login attribute based on the name and surname attributes.

        The login is generated by capitalizing the first letter of the name and converting the surname to lowercase.
        """
        self.login = self.name[0].capitalize() + self.surname.lower()